kind: Service
apiVersion: v1
metadata:
  name: iperf3
  labels:
    app: iperf3
  annotations:
    io.cilium/lb-ipam-ips: 10.0.100.101
spec:
  selector:
    app: iperf3
  ports:
    - protocol: TCP
      port: 5201
      name: iperf3
  type: LoadBalancer
